name: Build and publish Python

on:
  workflow_dispatch:
    inputs:
      python_version:
        required: true
        type: string
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string

jobs:
  build:
    name: Build ${{ inputs.python_version }}
    uses: ./.github/workflows/build_python.yml
    with:
      python_version: ${{ inputs.python_version }}

  publish:
    name: Publish ${{ inputs.python_version }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: python
          path: /tmp/python/

      - name: Pick tag
        run: |
          pattern="/tmp/python/*.tar.gz"
          files=( $pattern )
          file="${files[0]}"
          echo "SELECTED_TAG=$(./scripts/pick_semver.sh $file)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/python/*.tar.gz
          tag_name: ${{ env.SELECTED_TAG }}
          body: "Python ${{ inputs.python_version }}"